
# config/logging/logging.yaml
version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s [%(levelname)s] %(name)s:%(lineno)d - %(funcName)s(): %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s %(pathname)s %(lineno)d"
  
  simple:
    format: "%(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  console_debug:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout
  
  file_info:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: /app/logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  file_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: /app/logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  file_debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: /app/logs/debug.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

loggers:
  app:
    level: DEBUG
    handlers: [console, file_info, file_error]
    propagate: false
  
  app.models:
    level: DEBUG
    handlers: [file_debug]
    propagate: true
  
  app.utils:
    level: INFO
    handlers: [file_info]
    propagate: true
  
  uvicorn:
    level: INFO
    handlers: [console, file_info]
    propagate: false
  
  uvicorn.access:
    level: INFO
    handlers: [file_info]
    propagate: false
  
  requests:
    level: WARNING
    handlers: [file_error]
    propagate: false
  
  urllib3:
    level: WARNING
    handlers: [file_error]
    propagate: false

root:
  level: INFO
  handlers: [console, file_info, file_error]